import { ELEMENTS } from "../data/elements";
import { CIV_TIERS } from "../data/civilisation";

export function buildInitState() {
  return {
    amounts:                ELEMENTS.map(() => 0),
    converters:             ELEMENTS.map(() => 0),
    totalClicks:            0,
    totalQuarksEarned:      0,
    totalMindsEver:         0,
    echoes:                 0,
    totalEchoesEarned:      0,
    purchasedUpgrades:      [],
    prestigeCount:          0,
    universeOverclockCount: 0,
    lastTick:               Date.now(),
    offlineSeconds:         0,
    log:                    ["Welcome to CosmoGenesis. Click Quarks to begin."],
    firedDiscoveries:       [],
    pendingDiscovery:       null,
    civUnlocked:            false,
    civAmounts:             CIV_TIERS.map(() => 0),
    civConverters:          CIV_TIERS.map(() => 0),
    culture:                0,
    totalCultureEver:       0,
    pendingEra:             null,
    firedEras:              [],
    eraChoices:             {},
    purchasedPolicies:      [],
    darkAgesCount:          0,
    pendingEraChoice:       null,
    civEchoStudyLevel:      0,
    cultureSurgeEndsAt:     0,
    cultureSurgeLastUsedAt: 0,
    relics:                 0,
    totalRelicsEarned:      0,
    purchasedRelicUpgrades: [],
    // ── Science tab ───────────────────────────────────────────────────────────
    sciUnlocked:            false,
    sciConverters:          Array(7).fill(0),
    sciAmounts:             Array(7).fill(0),
    science:                0,
    totalScienceEver:       0,
    sciEra:                 0,
    sciPaths:               {},
    sciDiscoveries:         [],
    sciWildcards:           {},
    paradigmShiftCount:     0,
    breakthroughs:          0,
    totalBreakthroughsEarned: 0,
    innovations:            0,
    totalInnovationsEarned: 0,
    purchasedInnovations:   [],
    purchasedBreakthroughs: [],
  };
}
